apiVersion: v1
kind: Deployment
# Defining the metadata i.e, name of this deployment
metadata:
 -name: front-end-deployemnt
# Defining the replica set i.e, no. instances kubernetes should provision
spec:
 replicas: 2
 selector:
  matchLebales:
   app: ecom-front
 template:
  metadata: 
   labels:
    app: ecom-front
  spec:
   containers:
    -name: front-end-container
     image: venkatf6/ecommerce-webapp
     ports:
      - containers:8080
     env:
      - name: PORT
        value: "8080"
